baseURL = "https://hellolijj.github.io/"
languageCode = "zh-CN"
title = "李俊君 个人博客"
theme = "hyde"

# 显示前70个中文文字 
hasCJKLanguage = true

[author]
  name = "沉醉不知归路"

[params]
  description = "热爱生活，热爱开源技术"
  subtitle = "热爱贡献"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "post"
    name = "技术博客"
    url = "/post/"
    weight = 1